import '@library/kit/src/theme/themes.scss';

import React from 'react';
import type { Metadata } from 'next';

import './global.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <title>hgjhgjh</title>

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      </head>
      <body>{children}</body>
    </html>
  );
}
